/** 
 * List of all the database models used in the application Aikamaatti. They aim to simplify the communication and the
 * interfacing between the backend and the client.
 */

/** 
 * Base Model all the other database models extend from as they all share the common functionality.
 */
interface IdentifierModel {
    /** 
     * Unique. Database ID. Generated by the database.
     */ 
    _id: string;

    /** 
     * Unixtime. When the document was created.
     */ 
    created: number;

    /** 
     * Unixtime. When the entry was last modified.
     */
    last_modified: number; 

    /** 
     * _id. Last UserModel _id who modified the document.
     */
    last_modifier_id: string;
}


interface SkillModel extends IdentifierModel {
    /** 
     * Name of the specific skill, talent or treatment the Employee can perform.
     */ 
    name: string;
}

interface EmployeeModel extends IdentifierModel {
    /** 
     * List of SkillModel._id's. 
     * What skills the Employee has, as in, what work the Employee can do. Change tires, fill tax forms, cut hair etc.
     */ 
    skill_ids: string[];

    /** 
     * First name of the Employee
     */ 
    first_name: string;

    /** 
     * Last name of the Employee
     */ 
    last_name: string;
}

/** 
 * Group can be; for example, a set of students, specialists or set of people that have a specific area of work.
 */
interface GroupModel extends IdentifierModel {
    /** 
     * List of GroupModel._id's.
     * Employees in the current group.
     */
    employee_ids: string[];

    /** 
     * Name of the group.
     */
    name: string;
}

interface ReservationModel extends IdentifierModel {
    /** 
     * Unixtime. Start of the reservation.
     */ 
    start: number;

    /** 
     * Unixtime. End of the reservation.
     */ 
    end: number;

    /** 
     * CustomerModel._id.
     * Id of the Customer for who did the reservation.
     */
    customer_id: string;
}

interface CustomerModel extends IdentifierModel {
    /**
     * EmployeeModel._id.
     * Employee who worked with the Customer, the employee the customer booked for talents/skills/expertise ABC.
     */
    employee_id: string; 
}